In [1]:
import numpy as np

In [2]:
#Sample labels
labelsamples= ["b1p1_m05","b1p1_m10","b1p1_m20","b1p1_m40","b1p5_m05","b1p5_m10","b1p5_m20","b1p5_m40","b10_m05","b10_m10","b10_m20","b10_m40"]

#txt files with signal strength, expected background and signal efficiency for each nuclear configuration model
infiles = ['Eff_Bkg_hA_BR.txt', 'Eff_Bkg_hA_ESF.txt', 'Eff_Bkg_hA_LFG.txt', 'Eff_Bkg_hN_BR.txt', 'Eff_Bkg_hN_ESF.txt', 'Eff_Bkg_hN_LFG.txt']

#function to read the list of txt files
def readtxt(infile_array):
    listloaded = [] 
    for infile in infile_array:
        listloaded.append(np.loadtxt(infile, usecols=(3,4), skiprows=1))
    return listloaded

In [3]:
optimals = readtxt(infiles) 

## 1: (b_cv - b_i)/b_cv ,   2: (eff_cv - eff_i)/eff_cv ##

In [20]:
(optimals[0][:][:]-optimals[1][:][:])/optimals[0][:][:]

array([[-0.6557377 , -0.36436231],
       [-0.50724638, -0.36459736],
       [-0.54794521, -0.37051928],
       [-0.48101266, -0.36685532],
       [-0.05360444, -0.16894143],
       [-0.05765766, -0.16894143],
       [-0.04424779, -0.16894143],
       [-0.04225352, -0.16898356],
       [-0.00265957, -0.0751304 ],
       [-0.00245098, -0.07177511],
       [ 0.21485411, -0.05784468],
       [-0.0026738 , -0.07204374]])

In [30]:
(1-((optimals[0][:][:]-optimals[5][:][:])/optimals[0][:][:]))*optimals[0][:][:]

array([[2.700000e-02, 1.576749e+03],
       [3.200000e-02, 1.514888e+03],
       [3.500000e-02, 1.656354e+03],
       [3.800000e-02, 1.766170e+03],
       [5.970000e-01, 8.608341e+03],
       [6.130000e-01, 8.608341e+03],
       [6.190000e-01, 8.608341e+03],
       [6.210000e-01, 8.608341e+03],
       [3.720000e-01, 2.913725e+03],
       [4.020000e-01, 3.233103e+03],
       [2.910000e-01, 1.606481e+03],
       [3.710000e-01, 2.588593e+03]])

In [4]:
1-((optimals[0][:][:]-optimals[2][:][:])/optimals[0][:][:])

array([[0.8852459 , 0.89653726],
       [0.88405797, 0.89246959],
       [0.91780822, 0.89980656],
       [0.88607595, 0.9007824 ],
       [1.00924214, 0.98040951],
       [1.01621622, 0.98040951],
       [1.00530973, 0.98040951],
       [1.00880282, 0.98036368],
       [1.00265957, 0.96824459],
       [0.99019608, 0.96991816],
       [0.13793103, 0.97290455],
       [1.00802139, 0.96793583]])

In [4]:
optimals[3][:][:]/optimals[0][:][:]

array([[0.55737705, 1.05366856],
       [0.57971014, 1.05458566],
       [0.60273973, 1.05000928],
       [0.60759494, 1.05027243],
       [1.10536044, 1.03010884],
       [1.0990991 , 1.03010884],
       [1.09380531, 1.03010884],
       [1.09683099, 1.03000332],
       [0.99202128, 1.01753982],
       [0.9754902 , 1.01915409],
       [0.77718833, 0.98921683],
       [0.99197861, 1.00918828]])