In [2]:
import numpy as np

In [3]:
#txt files with signal strength, expected background and signal efficiency for each nuclear configuration model
infiles = ['Eff_Bkg_hA_BR.txt', 'Eff_Bkg_hA_ESF.txt', 'Eff_Bkg_hA_LFG.txt', 'Eff_Bkg_hN_BR.txt', 'Eff_Bkg_hN_ESF.txt', 'Eff_Bkg_hN_LFG.txt']

#function to read the list of txt files
def readtxt(infile_array):
    listloaded = [] 
    for infile in infile_array:
        listloaded.append(np.loadtxt(infile, usecols=(3,4), skiprows=1))
    return listloaded

In [4]:
optimals = readtxt(infiles) 

In [7]:
round(optimals[0][0][1])

1784

In [18]:
optimals[0][:][:]

array([[6.100000e-02, 1.783763e+03],
       [6.900000e-02, 1.721606e+03],
       [7.300000e-02, 1.869873e+03],
       [7.900000e-02, 1.992066e+03],
       [5.410000e-01, 8.883339e+03],
       [5.550000e-01, 8.883339e+03],
       [5.650000e-01, 8.883339e+03],
       [5.680000e-01, 8.884249e+03],
       [3.760000e-01, 2.982641e+03],
       [4.080000e-01, 3.310103e+03],
       [3.770000e-01, 1.712206e+03],
       [3.740000e-01, 2.653055e+03]])

## 1: (b_cv - b_i)/b_cv ,   2: (eff_cv - eff_i)/eff_cv ##

In [20]:
(optimals[0][:][:]-optimals[1][:][:])/optimals[0][:][:]

array([[-0.6557377 , -0.36436231],
       [-0.50724638, -0.36459736],
       [-0.54794521, -0.37051928],
       [-0.48101266, -0.36685532],
       [-0.05360444, -0.16894143],
       [-0.05765766, -0.16894143],
       [-0.04424779, -0.16894143],
       [-0.04225352, -0.16898356],
       [-0.00265957, -0.0751304 ],
       [-0.00245098, -0.07177511],
       [ 0.21485411, -0.05784468],
       [-0.0026738 , -0.07204374]])

In [21]:
(optimals[0][:][:]-optimals[2][:][:])/optimals[0][:][:]

array([[1.0100000e-01, 2.4336990e+03],
       [1.0400000e-01, 2.3492990e+03],
       [1.1300000e-01, 2.5626970e+03],
       [1.1700000e-01, 2.7228660e+03],
       [5.7000000e-01, 1.0384103e+04],
       [5.8700000e-01, 1.0384103e+04],
       [5.9000000e-01, 1.0384103e+04],
       [5.9200000e-01, 1.0385541e+04],
       [3.7700000e-01, 3.2067280e+03],
       [4.0900000e-01, 3.5476860e+03],
       [2.9600000e-01, 1.8112480e+03],
       [3.7500000e-01, 2.8441910e+03]])

In [22]:
(optimals[0][:][:]-optimals[3][:][:])/optimals[0][:][:]

array([[ 0.44262295, -0.05366856],
       [ 0.42028986, -0.05458566],
       [ 0.39726027, -0.05000928],
       [ 0.39240506, -0.05027243],
       [-0.10536044, -0.03010884],
       [-0.0990991 , -0.03010884],
       [-0.09380531, -0.03010884],
       [-0.09683099, -0.03000332],
       [ 0.00797872, -0.01753982],
       [ 0.0245098 , -0.01915409],
       [ 0.22281167,  0.01078317],
       [ 0.00802139, -0.00918828]])

In [23]:
(optimals[0][:][:]-optimals[4][:][:])/optimals[0][:][:]

array([[-0.06557377, -0.46096707],
       [ 0.04347826, -0.46658469],
       [ 0.05479452, -0.45917129],
       [ 0.06329114, -0.47001154],
       [-0.22920518, -0.2441036 ],
       [-0.21621622, -0.2441036 ],
       [-0.19823009, -0.2441036 ],
       [-0.19366197, -0.24422526],
       [ 0.01595745, -0.08369093],
       [ 0.01470588, -0.08456051],
       [ 0.23607427, -0.095961  ],
       [ 0.01069519, -0.08152677]])

In [24]:
(optimals[0][:][:]-optimals[5][:][:])/optimals[0][:][:]

array([[ 0.55737705,  0.11605466],
       [ 0.53623188,  0.12007277],
       [ 0.52054795,  0.11418904],
       [ 0.51898734,  0.11339785],
       [-0.10351201,  0.0309566 ],
       [-0.1045045 ,  0.0309566 ],
       [-0.09557522,  0.0309566 ],
       [-0.09330986,  0.03105586],
       [ 0.0106383 ,  0.0231057 ],
       [ 0.01470588,  0.02326212],
       [ 0.22811671,  0.06174783],
       [ 0.00802139,  0.02429727]])

In [30]:
(1-((optimals[0][:][:]-optimals[5][:][:])/optimals[0][:][:]))*optimals[0][:][:]

array([[2.700000e-02, 1.576749e+03],
       [3.200000e-02, 1.514888e+03],
       [3.500000e-02, 1.656354e+03],
       [3.800000e-02, 1.766170e+03],
       [5.970000e-01, 8.608341e+03],
       [6.130000e-01, 8.608341e+03],
       [6.190000e-01, 8.608341e+03],
       [6.210000e-01, 8.608341e+03],
       [3.720000e-01, 2.913725e+03],
       [4.020000e-01, 3.233103e+03],
       [2.910000e-01, 1.606481e+03],
       [3.710000e-01, 2.588593e+03]])

In [32]:
optimals[5][:][:]

array([[2.700000e-02, 1.576749e+03],
       [3.200000e-02, 1.514888e+03],
       [3.500000e-02, 1.656354e+03],
       [3.800000e-02, 1.766170e+03],
       [5.970000e-01, 8.608341e+03],
       [6.130000e-01, 8.608341e+03],
       [6.190000e-01, 8.608341e+03],
       [6.210000e-01, 8.608341e+03],
       [3.720000e-01, 2.913725e+03],
       [4.020000e-01, 3.233103e+03],
       [2.910000e-01, 1.606481e+03],
       [3.710000e-01, 2.588593e+03]])

In [27]:
(optimals[0][0][:]-optimals[5][0][:])/optimals[0][0][:]

array([0.55737705, 0.11605466])

In [28]:
optimals[0][0][:]

array([6.100000e-02, 1.783763e+03])

In [42]:
1-((optimals[0][:][:]-optimals[1][:][:])/optimals[0][:][:])

array([[1.6557377 , 1.36436231],
       [1.50724638, 1.36459736],
       [1.54794521, 1.37051928],
       [1.48101266, 1.36685532],
       [1.05360444, 1.16894143],
       [1.05765766, 1.16894143],
       [1.04424779, 1.16894143],
       [1.04225352, 1.16898356],
       [1.00265957, 1.0751304 ],
       [1.00245098, 1.07177511],
       [0.78514589, 1.05784468],
       [1.0026738 , 1.07204374]])